services:
  rabbitmq:
    image: rabbitmq:3.11.13-management
    hostname: 'rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - rabbitmq_data:/var/lib/rabbitmq/
        - rabbitmq_log:/var/log/rabbitmq/
    networks:
        - rabbitmq_go_net
volumes:
    rabbitmq_data:
    rabbitmq_log:
networks:
  rabbitmq_go_net:
    driver: bridge
